"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var OpCode;
(function (OpCode) {
    OpCode[OpCode["OPERATION_SET"] = 1] = "OPERATION_SET";
    OpCode[OpCode["OPERATION_ADD"] = 2] = "OPERATION_ADD";
    OpCode[OpCode["OPERATION_SUB"] = 3] = "OPERATION_SUB";
    OpCode[OpCode["OPERATION_MUL"] = 4] = "OPERATION_MUL";
    OpCode[OpCode["OPERATION_MLI"] = 5] = "OPERATION_MLI";
    OpCode[OpCode["OPERATION_DIV"] = 6] = "OPERATION_DIV";
    OpCode[OpCode["OPERATION_DVI"] = 7] = "OPERATION_DVI";
    OpCode[OpCode["OPERATION_MOD"] = 8] = "OPERATION_MOD";
    OpCode[OpCode["OPERATION_MDI"] = 9] = "OPERATION_MDI";
    OpCode[OpCode["OPERATION_AND"] = 10] = "OPERATION_AND";
    OpCode[OpCode["OPERATION_BOR"] = 11] = "OPERATION_BOR";
    OpCode[OpCode["OPERATION_XOR"] = 12] = "OPERATION_XOR";
    OpCode[OpCode["OPERATION_SHR"] = 13] = "OPERATION_SHR";
    OpCode[OpCode["OPERATION_ASR"] = 14] = "OPERATION_ASR";
    OpCode[OpCode["OPERATION_SHL"] = 15] = "OPERATION_SHL";
    OpCode[OpCode["OPERATION_IFB"] = 16] = "OPERATION_IFB";
    OpCode[OpCode["OPERATION_IFC"] = 17] = "OPERATION_IFC";
    OpCode[OpCode["OPERATION_IFE"] = 18] = "OPERATION_IFE";
    OpCode[OpCode["OPERATION_IFN"] = 19] = "OPERATION_IFN";
    OpCode[OpCode["OPERATION_IFG"] = 20] = "OPERATION_IFG";
    OpCode[OpCode["OPERATION_IFA"] = 21] = "OPERATION_IFA";
    OpCode[OpCode["OPERATION_IFL"] = 22] = "OPERATION_IFL";
    OpCode[OpCode["OPERATION_IFU"] = 23] = "OPERATION_IFU";
    OpCode[OpCode["OPERATION_ADX"] = 26] = "OPERATION_ADX";
    OpCode[OpCode["OPERATION_SBX"] = 27] = "OPERATION_SBX";
    OpCode[OpCode["OPERATION_STI"] = 30] = "OPERATION_STI";
    OpCode[OpCode["OPERATION_STD"] = 31] = "OPERATION_STD";
    OpCode[OpCode["OPERATION_JSR"] = 1] = "OPERATION_JSR";
    OpCode[OpCode["OPERATION_INT"] = 8] = "OPERATION_INT";
    OpCode[OpCode["OPERATION_IAG"] = 9] = "OPERATION_IAG";
    OpCode[OpCode["OPERATION_IAS"] = 10] = "OPERATION_IAS";
    OpCode[OpCode["OPERATION_RFI"] = 11] = "OPERATION_RFI";
    OpCode[OpCode["OPERATION_IAQ"] = 12] = "OPERATION_IAQ";
    OpCode[OpCode["OPERATION_HWN"] = 16] = "OPERATION_HWN";
    OpCode[OpCode["OPERATION_HWQ"] = 17] = "OPERATION_HWQ";
    OpCode[OpCode["OPERATION_HWI"] = 18] = "OPERATION_HWI";
})(OpCode = exports.OpCode || (exports.OpCode = {}));
//# sourceMappingURL=OpCode.js.map