
export enum OpCode {
    OPERATION_SET = 0x01,
    OPERATION_ADD = 0x02,
    OPERATION_SUB = 0x03,
    OPERATION_MUL = 0x04,
    OPERATION_MLI = 0x05,
    OPERATION_DIV = 0x06,
    OPERATION_DVI = 0x07,
    OPERATION_MOD = 0x08,
    OPERATION_MDI = 0x09,
    OPERATION_AND = 0x0a,
    OPERATION_BOR = 0x0b,
    OPERATION_XOR = 0x0c,
    OPERATION_SHR = 0x0d,
    OPERATION_ASR = 0x0e,
    OPERATION_SHL = 0x0f,

    OPERATION_IFB = 0x10,
    OPERATION_IFC = 0x11,
    OPERATION_IFE = 0x12,
    OPERATION_IFN = 0x13,
    OPERATION_IFG = 0x14,
    OPERATION_IFA = 0x15,
    OPERATION_IFL = 0x16,
    OPERATION_IFU = 0x17,

    OPERATION_ADX = 0x1a,
    OPERATION_SBX = 0x1b,

    OPERATION_STI = 0x1e,
    OPERATION_STD = 0x1f,

    OPERATION_JSR = 0x01,
    OPERATION_INT = 0x08,
    OPERATION_IAG = 0x09,
    OPERATION_IAS = 0x0a,
    OPERATION_RFI = 0x0b,
    OPERATION_IAQ = 0x0c,

    OPERATION_HWN = 0x10,
    OPERATION_HWQ = 0x11,
    OPERATION_HWI = 0x12
}